#!/bin/bash

RC=23
while [ $RC == 23 ]; do
    python3 groebner.py --timeout 500 --bench-csv benchmark_random_truth_table_network103.csv
    RC=$?
done

# python3 groebner.py --timeout 120 --bench-csv benchmark_random_regular_network.csv

#python3 example1.py

# f3 = x2*x3+x6
#    f4 = x20+x7*x11